### ISSUE TITLE
Data is not being displayed on the dashboard

### ISSUE THREAD

**Issue by dinesh-cyanam** [zeman/data-whare#1]
Saw your post on Reddit a few months back and responded but never got to installing it. Would like to work with you to help you test. I'm running this on a VM and followed the instructions and was able to build successfully and got the UI up and running. I added my TeslaFi API key and my Enphase Envoy IP address but do not see any data on the UI. Are there some logs I can look into?

Note: In its current form, the build will fail during the `./vendor/bin/sail up -d` step. This is because the php packages required by Laravel/Sail are no longer supported on Ubuntu 21.04 as it is EOL. We will need to switch to Ubuntu 21.10 and get those php packages. This code was checked in 10 days back to the Laravel/Sail repo but is not in their docker image yet (I think). So, I checked out the repo and replaced the files in the `data-whare/vendor/laravel/sail/runtimes` with the latest runtime files from the https://github.com/laravel/sail repo and the build finished successfully.

P.S. I also have a Rainmachine if you would like to integrate that as well.

**Comment by zeman** [comment]
Thanks for the heads up on the Ubuntu and Sail changes. I'll test it out once the next version of Sail is released and update the instructions.

I've just pushed a fix for the Envoy collector so if you `git pull` in the main directory it should start using the IP you specified.

**Comment by dinesh-cyanam** [comment]
Thank you. That helped and I can now see the solar data but don't see anything for the car data. Double-checked my TeslaFi token and also have the right permissions set. Also, I was able to hit the API and get JSON output.

<img width="1673" alt="Screen Shot 2022-03-26 at 4 52 36 PM" src="https://user-images.githubusercontent.com/65779696/160256686-7ebcadeb-9355-4393-babe-a69338b43470.png">

**Comment by zeman** [comment]
Car data is only shown when the car is charging. I'd rather not hit the Teslafi API every minute when the car is not charging.

**Comment by dinesh-cyanam** [comment]
Makes sense. I have it all working. If I see an issue and/or have suggestions, I will open another ticket. Thank you.

**Comment by zeman** [comment]
Great, thanks for trying the project out!
